name: Deploy App to Production

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Frontend Image
        run: |
          docker build --build-arg ENV=production -t ${{ secrets.DOCKER_HUB_USERNAME }}/firstry-production-front:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/firstry-production-front:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd FIRSTRY

            docker compose pull
            docker compose up -p firstry-prod -d
            docker system prune -f
