name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - master  # Trigger only on PR to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set the version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Update environment file
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  firebaseConfig: {" >> src/environments/environment.prod.ts
          echo "    apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> src/environments/environment.prod.ts
          echo "    authDomain: '${{ secrets.AUTH_DOMAIN }}'," >> src/environments/environment.prod.ts
          echo "    projectId: '${{ secrets.PROJECT_ID }}'," >> src/environments/environment.prod.ts
          echo "    storageBucket: '${{ secrets.STORAGE_BUCKET }}'," >> src/environments/environment.prod.ts
          echo "    messagingSenderId: '${{ secrets.MESSAGING_SENDER_ID }}'," >> src/environments/environment.prod.ts
          echo "    appId: '${{ secrets.APP_ID }}'," >> src/environments/environment.prod.ts
          echo "    measurementId: '${{ secrets.MEASUREMENT_ID }}'," >> src/environments/environment.prod.ts
          echo "  }," >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Build Angular app
        run: npm run build --prod

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers, trusted
