name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - master  # Trigger only on PR to the main branch

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set the version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Update environment file
        env: # Set the secret as an input
          secret_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          secret_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          secret_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          secret_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          secret_MESSAGING_SENDER_IDY: ${{ secrets.MESSAGING_SENDER_ID }}
          secret_APP_ID: ${{ secrets.APP_ID }}
          secret_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
        run: |
          sed -i 's/FIREBASE_API_KEY/"$secret_FIREBASE_API_KEY"/g' src/environments/environment.prod.ts 
          sed -i 's/AUTH_DOMAIN/secret_AUTH_DOMAIN/g' src/environments/environment.prod.ts 
          sed -i 's/PROJECT_ID/secret_PROJECT_ID/g' src/environments/environment.prod.ts 
          sed -i 's/STORAGE_BUCKET/secret_STORAGE_BUCKET/g' src/environments/environment.prod.ts 
          sed -i 's/MESSAGING_SENDER_ID/secret_MESSAGING_SENDER_ID/g' src/environments/environment.prod.ts 
          sed -i 's/APP_ID/secret_APP_ID/g' src/environments/environment.prod.ts 
          sed -i 's/MEASUREMENT_ID/secret_MEASUREMENT_ID/g' src/environments/environment.prod.ts 
          echo src/environments/environment.prod.ts 

      - name: Build Angular app
        run: npm run build --prod

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers, trusted
